<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\iMirror.Core\iMirror.Core.csproj" />
    <ProjectReference Include="..\iMirror.Bluetooth\iMirror.Bluetooth.csproj" />
  </ItemGroup>
</Project>
